POST http://localhost:8080/events
Content-Type: application/json

{
	"name": "EVENT MARCO LOCO",
	"description": "Test Description",
	"location": "Test Location",
	"date_time": "2021-01-01T00:00:00Z"
}