DELETE http://localhost:8080/events/6af48543-1a13-46c9-a563-939d2c5e7f97
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QHRlc3QuY29tIiwiZXhwIjoxNzQ0Njg4MTUwLCJpZCI6IjliNjU0OTYwLWM2NDYtNDNlMS1iNWY2LWUyZGRiYTI5MTJiNSJ9.M8Kj0c-m-iOhRz-oQO10XNNb7owhriHSO498dLe_do4