PUT http://localhost:8080/events/6924b92b-049c-4424-991d-627b750f8481
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QHRlc3QuY29tIiwiZXhwIjoxNzQ0Njg3NjkxLCJpZCI6IjliNjU0OTYwLWM2NDYtNDNlMS1iNWY2LWUyZGRiYTI5MTJiNSJ9.ne4U4pyPr0JLj2ARUg-20rsRb7KXednGP_QpwqOoeoo

{
	"name": "FLOW GAMES LALALALAL",
	"description": "Updated description",
	"location": "Updated location", 
	"date_time": "2025-04-12T10:00:00Z"
}
